### PR TITLE
Add support for intraday extended queries.

### PR DESCRIPTION
**Pull request by Sciguymjm**
Loads data from the API that only support csv queries, so ignores the user's selected format temporarily, and uses pd.read_csv to load it into a datatable in a similar format to the main intraday query.

### CODE REVIEW

**Comment by twopirllc** [comment]
Hello @Sciguymjm,

Great! Thanks for the contribution! I will try and roll it in soon.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @Sciguymjm,

I put up the inclusion of ```intraday_extended``` in the _Latest Version_. Please give it a go and let me know before I push it to **pypi** when you get a chance.
```sh
$ pip install -U git+https://github.com/twopirllc/AlphaVantageAPI
```

Thanks for the contribution.

Kind Regards,
KJ

**Comment by Sciguymjm** [comment]
Hi @twopirllc, seems to work for me in my development project. Thanks for including it so quickly!

**Comment by twopirllc** [comment]
Hi @Sciguymjm,

I apologize for the delay. Thanks for verifying and promptly informing me, I appreciate it. I will try and push to **pypi** soon.

Thanks,
KJ

**Pull request merged**
